# Working directory to checkout Git to
working_directory: C:/Users/dylan/OneDrive/Documents/Projects/PyCharm/csc4006-project-testing-repo/

# Provides settings for repo to perform analysis on
repo:
  type: remote
  remote: https://gitlab.dylanwilson.dev/dylan/led-display-controller
  local: C:/Users/dylan/OneDrive/Documents/Projects/PyCharm/csc4006-project-testing-repo

docker:
  analysis_image: mribeiro/cloc
